"""empty message

Revision ID: 80e54293e6c2
Revises: e2f089dc1ea8
Create Date: 2020-11-29 19:52:57.112741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e54293e6c2'
down_revision = 'e2f089dc1ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pbls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academicYear', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pbls', schema=None) as batch_op:
        batch_op.drop_column('academicYear')

    # ### end Alembic commands ###
