"""empty message

Revision ID: 855e7acfc2d6
Revises: fc26f3d8fbd7
Create Date: 2020-09-16 18:06:23.392054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855e7acfc2d6'
down_revision = 'fc26f3d8fbd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apiKeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apiKey', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_apiKeys'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apiKeys')
    # ### end Alembic commands ###
