"""empty message

Revision ID: 9f824784771b
Revises: 6fa9a49ab57a
Create Date: 2020-09-03 17:08:15.579732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f824784771b'
down_revision = '6fa9a49ab57a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('p2mtTemplates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('templateTitle', sa.String(length=255), nullable=True),
    sa.Column('emailSubject', sa.String(length=255), nullable=True),
    sa.Column('templateContent', sa.Text(), nullable=True),
    sa.Column('sendToStudent', sa.Boolean(), nullable=True),
    sa.Column('sendToParent', sa.Boolean(), nullable=True),
    sa.Column('sendToTeacher', sa.Boolean(), nullable=True),
    sa.Column('intervention_id', sa.Integer(), nullable=True),
    sa.Column('interventionLevel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['intervention_id'], ['InterventionType.id'], name=op.f('fk_p2mtTemplates_intervention_id_InterventionType')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_p2mtTemplates'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('p2mtTemplates')
    # ### end Alembic commands ###
