"""empty message

Revision ID: b788e871b049
Revises: 80e54293e6c2
Create Date: 2020-11-29 22:36:05.688226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b788e871b049'
down_revision = '80e54293e6c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PblTeams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academicYear', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PblTeams', schema=None) as batch_op:
        batch_op.drop_column('academicYear')

    # ### end Alembic commands ###
