"""empty message

Revision ID: d4f6c829ccec
Revises: d76bd11be4d8
Create Date: 2020-11-29 14:43:58.109980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d4f6c829ccec"
down_revision = "d76bd11be4d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Pbls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("className", sa.String(length=50), nullable=True),
        sa.Column("schoolYear", sa.Integer(), nullable=True),
        sa.Column("semester", sa.String(length=20), nullable=True),
        sa.Column("quarter", sa.Integer(), nullable=True),
        sa.Column("pblNumber", sa.Integer(), nullable=True),
        sa.Column("pblName", sa.String(length=100), nullable=True),
        sa.Column("pblSponsor", sa.String(length=100), nullable=True),
        sa.Column("pblComments", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Pbls")),
    )
    op.create_table(
        "PblEvents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pbl_id", sa.Integer(), nullable=False),
        sa.Column("eventCategory", sa.String(length=100), nullable=True),
        sa.Column("confirmed", sa.Boolean(), nullable=True),
        sa.Column("eventDate", sa.Date(), nullable=True),
        sa.Column("startTime", sa.Time(), nullable=True),
        sa.Column("endTime", sa.Time(), nullable=True),
        sa.Column("eventLocation", sa.String(length=100), nullable=True),
        sa.Column("eventStreetAddress1", sa.String(length=100), nullable=True),
        sa.Column("eventStreetAddress2", sa.String(length=100), nullable=True),
        sa.Column("eventCity", sa.String(length=100), nullable=True),
        sa.Column("eventState", sa.String(length=100), nullable=True),
        sa.Column("eventZip", sa.String(length=10), nullable=True),
        sa.Column("eventComments", sa.Text(), nullable=True),
        sa.Column("googleCalendarEventID", sa.String(length=250), nullable=True),
        sa.ForeignKeyConstraint(
            ["pbl_id"],
            ["Pbls.id"],
            name=op.f("fk_PblEvents_pbl_id_Pbls"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_PblEvents")),
    )
    op.create_table(
        "PblTeams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("className", sa.String(length=50), nullable=True),
        sa.Column("schoolYear", sa.Integer(), nullable=True),
        sa.Column("semester", sa.String(length=20), nullable=True),
        sa.Column("quarter", sa.Integer(), nullable=True),
        sa.Column("pblNumber", sa.Integer(), nullable=True),
        sa.Column("pblTeamNumber", sa.Integer(), nullable=True),
        sa.Column("chattStateANumber", sa.String(length=20), nullable=False),
        sa.Column("pbl_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chattStateANumber"],
            ["Student.chattStateANumber"],
            name=op.f("fk_PblTeams_chattStateANumber_Student"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pbl_id"],
            ["Pbls.id"],
            name=op.f("fk_PblTeams_pbl_id_Pbls"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_PblTeams")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("PblTeams")
    op.drop_table("PblEvents")
    op.drop_table("Pbls")
    # ### end Alembic commands ###
