"""empty message

Revision ID: d76bd11be4d8
Revises: 855e7acfc2d6
Create Date: 2020-09-17 10:11:36.048206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd76bd11be4d8'
down_revision = '855e7acfc2d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('InterventionLog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parentNotification', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('studentNotification', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('InterventionLog', schema=None) as batch_op:
        batch_op.drop_column('studentNotification')
        batch_op.drop_column('parentNotification')

    # ### end Alembic commands ###
