"""empty message

Revision ID: e2f089dc1ea8
Revises: d4f6c829ccec
Create Date: 2020-11-29 18:59:26.807285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f089dc1ea8'
down_revision = 'd4f6c829ccec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pbls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pblSponsorEmail', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pblSponsorPersonName', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pblSponsorPhone', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pbls', schema=None) as batch_op:
        batch_op.drop_column('pblSponsorPhone')
        batch_op.drop_column('pblSponsorPersonName')
        batch_op.drop_column('pblSponsorEmail')

    # ### end Alembic commands ###
