"""empty message

Revision ID: fc26f3d8fbd7
Revises: 9f824784771b
Create Date: 2020-09-09 15:29:26.303896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc26f3d8fbd7'
down_revision = '9f824784771b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminSettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enableLiveEmail', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adminSettings'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adminSettings')
    # ### end Alembic commands ###
